### 회원가입
POST localhost:8083/api/account/signup
Content-Type: application/json

{
  "loginId": "user",
  "password": "user123",
  "name": "유저",
  "email": "user@example.com"
}

### 회원 정보 조회
GET localhost:8083/api/account/1
X-USER-ID: 1